### ISSUE TITLE
Supporting Latched Driving

### ISSUE THREAD

**Issue by aaamorgan** [lucimobility/wheelchair-digital-interface#14]
Latched driving is a feature that can currently be setup on through the power wheelchair electronics. It is most commonly used with Sip N Puff inputs. There are two types of latch modes:
1. Step - A forwards driving input increases the latched speed stepwise. Moving it backwards reduces the speed until 0. Holding a backwards drive input fully cancels latch. The number of steps may be configurable.
2. Cruise - maintains whatever forward speed it’s at when the input is released. Moving the input back stops. Moving the input forward can increase latched speed

Latched driving can be setup for forwards or backwards driving. I can see the WDI interfacing with latched driving in a few ways:
1. WDI has no knowledge of latch mode and is still purely a chair drive setting. Regular drive inputs through the WDI should operate latch mode correctly.
2. WDI has a particular button mapped that puts the driving in latched mode.
3. WDI has alternate mappings for controlling latched driving. E.g. Shift + 'w' latches driving forward
4. WDI has a way to configure it to switch normal drive inputs to control latched driving.
5. WDI has a mapping to hold current forward/reverse input value. (more similar to car cruise control)

In my opinion, this falls outside the domain of the WDI because it starts crossing the line into defining how the drive inputs are translated into motion. There are several settings involved with latch, such as step vs. cruise, how long a reverse command must be given to stop instead of just slow down, and how long latched driving can go without timing out. It makes more sense to me to leave latch on either side of the WDI. Either the wheelchair electronics handle turning normal driving inputs into latched ones, or the input device natively has latch support.

Open to other options and opinions.

**Comment by aaamorgan** [comment]
I also just found this tool, and it may be possible to use it to make any HID support latch. https://github.com/jfedor2/hid-remapper/tree/master

**Comment by shawnsexton** [comment]
I agree that latch is a wheelchair manufacturer feature and as such I don't think it should be an explicit WDI feature. Users can engage latch if it is configured in their wheelchair settings through normal drive controls. Manufacturers always have the option to use manufacturer specific WDI commands for latch if they think it is necessary.

**Comment by jeredhdean** [comment]
Based on the discussion above, calling this a decision: Latch will not be an explicit feature of WDI. It will be handled above or below the interface by manufacturer devices. 

Thanks to everyone for the input!
