### ISSUE TITLE
Can we add additional information to the WDI for drive and display?

### ISSUE THREAD

**Issue by jeredhdean** [lucimobility/wheelchair-digital-interface#2]
Raised by Northwestern Argalab: Could the WDI include information on the current speed, acceleration, speed settings, mode etc. of the chair for use by active systems and/or to display?

**Comment by aaamorgan** [comment]
Based on meetings with Northwestern on August 21, 2024, it has been proposed that WDI feedback should be limited to built-in HID functionalities. These will focus on lights, sounds, and haptics that could be part of an input device.
