### ISSUE TITLE
Call out enhancements in relation to existing standards? 

### ISSUE THREAD

**Issue by doudulac** [lucimobility/wheelchair-digital-interface#4]
Call out the existing RESNA / ANSI / ISO, or manufacturer specific, standards that WDI solves, enhances, or updates. For example, how does WDI improve upon [M3S](https://ieeexplore.ieee.org/document/536774), [RESNA WC-2](https://www.resna.org/Portals/0/AT_WC2_SellSheet_2_10_21.pdf)?

**Comment by jeredhdean** [comment]
@doudulac great suggestion. I'll add an explicit section to the Readme responding to this question and add you as a reviewer on the PR. M3S was never adopted by industry and is a dead spec for all intents and purposes. WC-2 (and ISO 7176) do not cover alternative access methods. There is a current "standard" around the 9-pin printer cable for alt drives that this would replace (or add too).
